package ase.rsse.apirec.transactions;

public enum NodeType {
	// composite types
	DelegateDeclaration,
	EventDeclaration,
	FieldDeclaration,
	MethodDeclaration,
	PropertyDeclaration,
	VariableDeclaration,
	Assignment,
	BreakStatement,
	ContinueStatement,
	ExpressionStatement,
	GotoStatement,
	LabelledStatement,
	ReturnStatement,
	ThrowStatement,
	EventSubscriptionStatement,
	DoLoop,
	ForEachLoop,
	ForLoop,
	IfElseBlock,
	LockBlock,
	SwitchBlock,
	TryBlock,
	UncheckedBlock,
	UnsafeBlock,
	UsingBlock,
	WhileLoop,
	BinaryExpression,
	CastExpression,
	CompletionExpression,
	ComposedExpression,
	IfElseExpression,
	IndexAccessExpression,
	InvocationExpression,
	LambdaExpression,
	TypeCheckExpression,
	UnaryExpression,
	LoopHeaderBlockExpression,
	ConstantValueExpression,
	NullExpression,
	ReferenceExpression,
	EventReference,
	FieldReference,
	IndexAccessReference,
	MethodReference,
	PropertyReference,
	VariableReference,
	UnknownExpression,
	UnknownStatement,
	// DelegateDeclaration
	DelegateTypeName,
	DelegateTypeFullName,
	NamespaceName,
	// MethodDeclaration
	MethodName,
	TypeParameterName,
	ParameterName,
	TypeName,
	Statement,
	// ApiRec Node Types
	VariableDeclarationStatement,
	ParameterizedType,
	SimpleType,
	SimpleName,
	VariableDeclarationFragement,
	ClassInstanceCreation,
	MethodInvocation,		
}
